테스트 PR
code-squad/javascript-review pull request #26
Opened 2018-03-05 07:36 UTC by sejungkim

테스트 및 hello world 출력

2018-03-05 07:47 UTC, crongro requested changes

2018-03-05 07:47 UTC, nigayo commented on hello.js
> +console.log("hello world");
log함수를 만들어서 지금 구현한 내용을 넣어보세요.

2018-03-06 02:04 UTC, sejungkim commented
로그 함수 완료!

2018-03-06 02:28 UTC, crongro approved these changes
로그함수 축하합니다!

2018-03-06 02:28 UTC, merged