Update README.md -일정추가
code-squad/javascript-review pull request #29
Opened 2018-03-07 06:55 UTC by antaehyeon

README 에 일정 카테고리를 추가하였습니다.
PR 테스트를 진행중입니다.

2018-03-07 08:40 UTC, crongro requested changes
첫커밋,첫PR 축하해요.

javascript  파일 하나 만들고, 
console.log ("hello world") 
추가해서 다시 commit/push 해보세요.

2018-03-08 07:25 UTC, crongro approved these changes

2018-03-08 07:27 UTC, nigayo commented
아 여기에 다각형넓이도 추가한거군요? 
다각형 넓이는 다른저장소에 하셔야해요. 

https://nextstep.camp/courses/-Kv05nt2H14q-C4t92uz/-KvHXtV65U4SzWfqc98p/lessons/-KvHYobyJhQkcnuecpPp

여기보면  github 저장소보이시죠?

2018-03-08 07:31 UTC, crongro requested changes
엄청난 정리를 하셨네요!

quiz만 리뷰내용대로 다시 구현해보세요.

2018-03-08 07:31 UTC, nigayo commented on README/다각형의 넓이-퀴즈풀이.md
> +   function GCD(x, y) {
네 이런 알고리즘을 찾아서 쓰는 건 좋아요.
재귀에 대한 이해를 꼭하셨기를 바라고요.

이번에는 이 알고리즘을 쓰지 않고 
숫자 반복을 하면서 구현해보세요.

2018-03-08 07:32 UTC, antaehyeon commented
아, 강의내용만 추가했고, 다각형의 넓이 코드부터 javaScript-polygon Repasitory에서 PR 날리도록 하겠습니다 :)

2018-03-08 07:33 UTC, antaehyeon commented on README/다각형의 넓이-퀴즈풀이.md
> +   function GCD(x, y) {
알겠습니다 :)

2018-03-08 07:53 UTC, merged