Hello Javascript Lecture Complete
code-squad/javascript-review pull request #3
Opened 2017-10-16 05:57 UTC by Eclatant

Lecture 관련 내용을 정리하여 PR 작성하였습니다.

2017-10-16 06:07 UTC, crongro requested changes
변경내용을 조금더 보강해보세요.

2017-10-16 06:07 UTC, nigayo commented on Eclatant/171016.md
> +  - 최대한 작게 자주 하는 것이 좋으며, 한 문장으로 표현할 수 있는 변화량이 생길 때마다 하는 것이 좋다고 생각한다
예시로 좋은 사이트를 찾아서 링크를 추가해보세요.

2017-10-16 06:07 UTC, nigayo commented on Eclatant/171016.md
> +  - ?!
몇몇 대규모 프로젝트를 찾아보거나, 주변에서 github를 어떻게 사용하는지 찾아보세요.

2017-10-16 06:07 UTC, nigayo commented on Eclatant/171016.md
> +  - `git commit -v`
-v 는 뭐에요?

2017-10-16 06:27 UTC, Eclatant commented on Eclatant/171016.md
> +  - `git commit -v`
@nigayo `-v` 옵션에 대한 링크를 첨부하였습니다.

2017-10-16 06:27 UTC, Eclatant commented on Eclatant/171016.md
> +  - 최대한 작게 자주 하는 것이 좋으며, 한 문장으로 표현할 수 있는 변화량이 생길 때마다 하는 것이 좋다고 생각한다
@nigayo 관련 아티클 두 개를 읽고 첨부하였습니다.

2017-10-16 06:27 UTC, Eclatant commented on Eclatant/171016.md
> +  - ?!
@nigayo 제일 대표적인 branch 전략인 git-flow 관련 링크를 첨부하였습니다.

2017-10-16 06:28 UTC, Eclatant commented
@nigayo 피드백을 반영하였습니다, 번거로우시겠지만 재리뷰 부탁드립니다...!

2017-10-16 07:12 UTC, nigayo commented on Eclatant/171016.md
> +  - 불편한 점은 존재하지 않음
과연불편함점이 없을까요?

2017-10-16 07:12 UTC, crongro approved these changes
잘하셨어요.

2017-10-16 07:12 UTC, merged

2017-10-16 07:26 UTC, Eclatant commented on Eclatant/171016.md
> +  - 불편한 점은 존재하지 않음
@nigayo 

불편한 점이 무엇인지 정말 모르겠습니다, 형상관리가 선택사항이라고 생각해보지 못한 것 같습니다...

2017-10-17 07:42 UTC, nigayo commented on Eclatant/171016.md
> +  - 불편한 점은 존재하지 않음
형상관리도구를 통한 협업개발자체가 귀찮고 어렵긴하죠. 
물론 이런거 없으면 더 어렵다는거.. ㅋ 협업의 어려움이죠 사실.