lotto.js project PR 보내드립니다.
code-squad/javascript-review pull request #62
Opened 2018-09-05 01:44 UTC by uoon-dev

2018-09-05 11:55 UTC, nigayo commented
로또 과제를 위한 branch 가 따로 있는데요,
https://github.com/code-squad/javascript-lotto

다음엔 이곳이 아닌 nextstep에 써있는 저장소로 PR보내주세요^^

이번엔 그냥 이곳에 리뷰남깁니다.

2018-09-05 12:06 UTC, crongro requested changes
잘 하셨어요. 
리뷰를 남겨드리니 다시 수정해보시고 push 해보세요.

2018-09-05 12:06 UTC, nigayo commented on lotto.js
> +buyLottos(2800);
money, price가 약간 불필요하게 두 개가 있어보여요.

let money = 2800;
buyLottos(money)  

이렇게만 해도 될 거 같습니다.

2018-09-05 12:06 UTC, nigayo commented on lotto.js
> +  money = price;
변수이름을 명사로 짓는건 잘하셨어요.
다만 변수 이름이 좀더 구체적이면 더 좋겠어요.
price가 로또 하나의 가격이라는 건 알 수 있긴한데요. lottoPrice 와 같은 게 더 낫죠.

2018-09-05 12:06 UTC, nigayo commented on lotto.js
> +  const luckyNumbers = setLuckyNumber([12, 25, 32, 41, 15, 6]);
당첨번호는 변경될 수 있는 것까지 생각하면 checkResult함수에 이렇게  코드를 적어두기보다는 인자로 받는 게 더 낫겠죠.
또한 요구사항은 없지만 랜덤하게 luckynumber를 만들 필요도 사실 있긴하고요.

2018-09-05 12:06 UTC, nigayo commented on lotto.js
> +const publishPapersByCount = (count = 0) => {
빈통을 만들고 있는 이 함수가 과연필요할까? 약간 그런생각이듭니다.
해야할일을 잘 나눠서 좋긴한데요, 성능을 생각해보면 불필요한 반복문을 좀더 줄이면 어떨까 생각이 드네요.
randomLotto를 발행할때 정해진갯수(6자리죠)만큼 반복을 돌게 만들면 프로그램이 좀더 연산을 적게 하는 게 아닐까 싶어서요 .

2018-09-05 12:06 UTC, nigayo commented on lotto.js
> +  const totalLotto = page.map(item => {
map과 map을 잘 쓰셨네요~  함수를 반환하는 함수~

2018-09-05 12:06 UTC, nigayo commented on lotto.js
> +  const papers = publishPapersByCount(count);
함수의 결과를 받아서 다른함수의 인자로 넣는 식으로 잘 하셨어요~
프로그램이 어떻게 동작하는지 buyLottos를 보면 알 수 있어서 좋습니다.

2018-09-05 23:02 UTC, crongro requested changes
전체적으로 금방 잘 개선하셨어요 👍 

다만, 
현재 구현하신 부분이 빈 배열을 만들어서 그 배열을 넘겨주고 무언가 채우는 방식인데요, 
빈 배열을 만드는 과정이 필요 없습니다. 
요 부분을 수정해보세요

2018-09-05 23:02 UTC, crongro commented on lotto.js
> +const shuffle = function* (array) {
generator 를 이해하셨나요?
혹시 잘 모르시면 이 동작이 좀 난해할 수 있지만, 무엇인지 한번 살펴보세요.

2018-09-05 23:02 UTC, nigayo commented on lotto.js
> +  const lottoNumberCounts = Array.from(new Array(45)).map(() => index++);
javascript 에서 배열을 자리를 미리 할당할 필요가 없습니다.
여기 로직이 없이 그냥 shuffle()를 호출하고, shuffle 에서는 45숫자만큼 반복을 돌면서 값을 채워도 될 거 같아요.

2018-09-05 23:02 UTC, nigayo commented on lotto.js
> +  const lottoNumberCounts = Array.from(new Array(45)).map(() => index++);
그리고 Array.from 을 쓰지 않아도 똑같은결과 같은데요.
Array.from은 배열같은 자료구조를 (function의 arguments같은)배열로 만드는 메서드입니다.

2018-09-05 23:02 UTC, nigayo commented on lotto.js
> +  const paper = Array.from((new Array(6)));
여기서도 paper에 미리 빈배열을 채울필요가 없습니다.

2018-09-06 01:50 UTC, uoon-dev commented on lotto.js
> +const shuffle = function* (array) {
해당 함수는 복붙.. 했습니다 ㅎㅎㅎ iterable protocol & generator를 공부하고 있긴 하는데 어렵네요 :)

2018-09-06 01:52 UTC, uoon-dev commented on lotto.js
> +  const lottoNumberCounts = Array.from(new Array(45)).map(() => index++);
https://stackoverflow.com/a/28599347/10175232
이 이슈 때문에 Array.from을 써줘야 했습니다. 일반 객체를 만들면 iterable 하지 않아서 map 함수가 안 돌더라구요 ㅜㅜ

2018-09-10 07:26 UTC, crongro approved these changes
수고하셨네요. 
제 생각에 map을 쓰기위해서 지금방식처럼 array를 생성하는건 약간 비효율로 보이네요.
잘하셨어요!

2018-09-10 07:26 UTC, merged